# Generated by Django 4.0.5 on 2022-06-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('country_code', models.CharField(max_length=20, verbose_name='country_code')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('desc', models.TextField(verbose_name='description')),
                ('from_date', models.DateField(verbose_name='from_date')),
                ('to_date', models.DateField(verbose_name='to_date')),
                ('price', models.FloatField(verbose_name='price')),
                ('from_city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='core.city')),
                ('to_city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(verbose_name='book_date')),
                ('is_payment_done', models.BooleanField(verbose_name='is_payment_done')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tour')),
            ],
        ),
    ]
