# Generated by Django 4.0.5 on 2022-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_code',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='country'),
        ),
    ]
