# Generated by Django 4.0.5 on 2022-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_city_country_code_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='locale',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='locale'),
        ),
    ]
